/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codegans.arreg;

import com.codegans.arreg.ui.PersonFilter;
import javafx.scene.Scene;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
import javafx.application.Application;

public class App extends Application {
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {
        VBox layout = new VBox();
        PersonFilter filter = new PersonFilter();

        layout.setFillWidth(true);
        layout.getChildren().add(filter.render());

        Scene scene = new Scene(layout);

        primaryStage.setScene(scene);
        primaryStage.show();
    }

    String getGreeting() {
        return "";
    }
}
