package com.codegans.arreg.model;

import com.codegans.arreg.I18n;

public enum Rank {
    PRIVATE(I18n.RANK_PRIVATE),
    PRIVATE_FIRST_CLASS(I18n.RANK_PRIVATE_FIRST_CLASS),
    JUNIOR_SERGEANT(I18n.RANK_JUNIOR_SERGEANT),
    SERGEANT(I18n.RANK_SERGEANT),
    SENIOR_SERGEANT(I18n.RANK_SENIOR_SERGEANT),
    CHIEF_SERGEANT(I18n.RANK_CHIEF_SERGEANT),
    STAFF_SERGEANT(I18n.RANK_STAFF_SERGEANT),
    MASTER_SERGEANT(I18n.RANK_MASTER_SERGEANT),
    SENIOR_MASTER_SERGEANT(I18n.RANK_SENIOR_MASTER_SERGEANT),
    CHIEF_MASTER_SERGEANT(I18n.RANK_CHIEF_MASTER_SERGEANT),
    JUNIOR_LIEUTENANT(I18n.RANK_JUNIOR_LIEUTENANT),
    LIEUTENANT(I18n.RANK_LIEUTENANT),
    SENIOR_LIEUTENANT(I18n.RANK_SENIOR_LIEUTENANT),
    CAPTAIN(I18n.RANK_CAPTAIN),
    MAJOR(I18n.RANK_MAJOR),
    LIEUTENANT_COLONEL(I18n.RANK_LIEUTENANT_COLONEL),
    COLONEL(I18n.RANK_COLONEL),
    BRIGADIER_GENERAL(I18n.RANK_BRIGADIER_GENERAL),
    MAJOR_GENERAL(I18n.RANK_MAJOR_GENERAL),
    LIEUTENANT_GENERAL(I18n.RANK_LIEUTENANT_GENERAL),
    GENERAL(I18n.RANK_GENERAL);

    private final I18n i18nKey;

    Rank(I18n i18nKey) {
        this.i18nKey = i18nKey;
    }

    public String get() {
        return i18nKey.get();
    }
}
