package com.codegans.arreg.model;

public enum Reason {
    HEALTH_ASSESSMENT,
    MEDICAL_TREATMENT,
    VACATION_REGULAR,
    VACATION_FAMILY,
    VACATION_MEDICAL,
    RECRUIT_REGULAR,
    DISMISS_REGULAR,
    DISMISS_MEDICAL,
    DISMISS_LETHAL,
    DISMISS_RUNAWAY,
    DISMISS_MIA,
    TRANSFER_REGULAR
}
